// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnGX7IGsYN3-dF_HR6WgUdFh9w7BdFugA',
    appId: '1:490438852604:web:e46c0094c0565a30e5bc79',
    messagingSenderId: '490438852604',
    projectId: 'story-c0de2',
    authDomain: 'story-c0de2.firebaseapp.com',
    storageBucket: 'story-c0de2.appspot.com',
    measurementId: 'G-GR4LFYZ7T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQeWJnestvLmjU2U6RqFTGG76dNfyEcZ4',
    appId: '1:490438852604:android:d4849426fc0482a6e5bc79',
    messagingSenderId: '490438852604',
    projectId: 'story-c0de2',
    storageBucket: 'story-c0de2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAuJ8FXmMqww_Ot7qNxBLowaz_Owj5Zoc',
    appId: '1:490438852604:ios:373948f37eb41f52e5bc79',
    messagingSenderId: '490438852604',
    projectId: 'story-c0de2',
    storageBucket: 'story-c0de2.appspot.com',
    iosClientId: '490438852604-c8j45b64nlkpjc6dmlujdg3d7r133l4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.story',
  );
}
